image: "rust:latest"

stages:
  - test
  - release

cache:
  paths:
    - target/

test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release
    - cargo publish --token $CRATES_TOKEN
  artifacts:
    name: $CI_COMMIT_TAG
    paths:
      - target/release/osoy
  release:
    tag_name: $CI_COMMIT_TAG
    name: Osoy $CI_COMMIT_TAG
    description: $CI_COMMIT_TAG
    assets:
      links:
        - name: osoy-$CI_COMMIT_TAG
          url: https://gitlab.com/osoy/osoy/-/artifacts/$CI_COMMIT_TAG
